--[[

************************************************************************

zhTW.lua

zhTW localization strings for Querier

File date: @file-date-iso@ 
Project version: @project-version@

Please update http://www.wowace.com/projects/querier/localization/zhTW/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.

************************************************************************

Please see http://www.wowace.com/projects/querier/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************

]]--


local debug = false
--@debug@
debug = true
--@end-debug@

local L = LibStub("AceLocale-3.0"):NewLocale("Querier", "enUS", true, debug)

if not L then return end

--@localization(locale="enUS", format="lua_additive_table", handle-unlocalized="english", escape-non-ascii=false, same-key-is-true=true)@